// Verified, route-specific eligibility and filing actions. Unknown routes stay review questions.
export const QUESTIONS={
 paReligiousSupport:['Is the institution primarily supported by its congregation, members or previous donors, government grants or contracts, or service fees?','Pennsylvania’s religious exclusion requires these primary support sources. A contribution amount alone does not answer this question.'],
 bonaFideReligious:['Is this a duly organized, bona fide religious institution or society?','A religious mission alone does not establish every state exclusion. Include an integral religious group only when the state definition covers it.'],
 paNoInurement:['Is the organization’s net income free of direct private benefit to any individual?','Paid staff alone do not establish private inurement. Choose Not sure if a compensation arrangement needs review.'],
 religion990:['Is the organization exempt from filing Form 990 because of its religious status?','Being a 501(c)(3) alone does not establish this federal return exclusion.'],
 coChurchEligible:['Does the organization fit Colorado’s federal church category or one of its listed church-related categories?','Includes qualifying churches, church associations, integrated auxiliaries and certain religious orders, mission societies and church schools. A religious mission alone is insufficient.'],
 caPrimaryInstitution:['Is the entity organized primarily as a religious organization, hospital or educational institution under California’s exemption definition?','A fundraising foundation is not automatically the institution itself. Schools must meet Corporations Code 10251 or the formal instruction, faculty/curriculum, enrolled students and classroom criteria in regulation 300.1. An IRS school label alone is insufficient.'],
 accreditation:['Is the school’s curriculum approved by a state or federal education authority, including accepted accreditation?','Used for Arkansas and Connecticut. General educational programming alone is insufficient.'],
 hospitalLicense:['Is this a nonprofit hospital licensed under the laws of a state?','Arkansas, Connecticut and Hawaii accept qualifying hospital licensing in their state or another state.'],
 paEducationApproval:['Is the curriculum approved by Pennsylvania’s Department of Education, directly or through accepted accreditation?','For a related foundation, the institution it supports must meet this condition.'],
 paHospitalRegulated:['Is the hospital or hospital foundation regulated by Pennsylvania’s Department of Health or Department of Public Welfare?','A hospital license in another state alone does not answer this Pennsylvania question.'],
 foundationControl:['Is the educational foundation directly responsible to the institution it supports?','Used for the Pennsylvania and West Virginia related educational foundation routes.'],
 hiEducationEligible:['Does the institution have licensing or accreditation recognized by Hawaii’s charity exemption rule?','Recognized bodies include regional school and college accreditors listed in the official Hawaii FAQ. Confirm the named accreditor in the source.'],
 hiFoundationEligible:['Is the foundation expressly authorized by a qualifying educational institution and primarily soliciting its parents, alumni, students and faculty?','Hawaii treats an associated foundation separately from the educational institution itself.'],
 flReligiousEligible:['Does the organization meet Florida’s religious institution definition?','Churches and bona fide religious groups are included. An integral affiliated group must not be primarily supported by appeals outside its own membership or congregation. See the linked definition.'],
 flEducationEligible:['Does the organization meet Florida’s educational institution definition?','Includes qualifying schools and colleges and certain nonprofit organizations raising funds for them. An educational mission alone is insufficient. See section 496.404(10).'],
 tnReligiousEligible:['Does the organization meet Tennessee’s bona fide religious institution definition?','The definition covers specified religious institutions and groups. Certain groups and integral affiliates must be exempt from Form 990; integral affiliates also have a membership support condition. See the definitions in section 48-101-501 (2024 Public Chapter 533).'],
 tnEducationEligible:['Does the institution or supporting organization meet Tennessee’s educational institution definition?','Qualifying faculty, curriculum, enrolled students, accreditation or education approval are required. Supporting organizations must fit the educational definition in section 48-101-501.'],
 tnHospitalRegulated:['Is the hospital regulated by Tennessee’s Department of Health?','A hospital license elsewhere alone does not establish this Tennessee exemption.'],
 scReligiousEligible:['Is this a congregation for divine worship, an integrated auxiliary, or a religious organization exempt from federal information returns because of its religious classification?','South Carolina excludes these entities from its charitable organization definition. This differs from its annual exemption application routes.'],
 scEducationAudience:['Are appeals limited to the institution’s students, families, alumni, faculty, trustees and other supportive constituencies described in South Carolina law?','The institutional route also excludes professional solicitors, fundraising counsel and commercial co-venturers.'],
 wiEducationEligible:['Does the institution or educational foundation fit Wisconsin’s specific educational exemption?','Examples include qualifying accredited postsecondary institutions, defined private schools, and institutions with authorized foundations soliciting only the listed educational constituencies. Confirm the exact route in the official FAQ.'],
 ctSoleBenefit:['Does the foundation solicit solely for a Connecticut-exempt religious institution, qualifying educational institution or licensed nonprofit hospital?','A foundation is not automatically treated as the institution it supports.'],
 scCompensationLimit:['Is every person performing organization functions paid no more than $500 annually for those services?','This South Carolina condition applies to all functions, including fundraising. Officers or members also must not receive the prohibited income or benefit.']
 ,miHospitalEntity:['Is this entity itself a licensed hospital, rather than a health system or other affiliate?','Michigan’s CTS-03 distinguishes the licensed hospital from its affiliates. A hospital-based foundation has a separate, narrower solicitation exemption.']
 ,flGrantmakerRegistered:['Is every nonprofit grantmaker duly registered with Florida’s Department of Agriculture and Consumer Services?','Florida’s grant-application exclusion requires government applications or applications to an eligible 501(c) grantmaker duly registered with the Department. Federal tax exemption alone is not enough.']
 ,ncEducationEligible:['Does the institution meet North Carolina’s approved education category?','Its curriculum must be approved or accredited by SACS or an equivalent regional accreditor, or it must comply with Chapter 115C Article 39. A foundation or department must have an established identity with such an institution.']
 ,ncHospitalEligible:['Is the hospital licensed under North Carolina Chapter 131E Article 5 or Chapter 122C Article 2?','For a foundation or department, it must have an established identity with that hospital, and the hospital board must authorize the solicitation and receive an accounting. A license elsewhere alone does not establish this route.']
 ,vaEducationEligible:['Does this entity meet Virginia’s educational exemption?','Qualifying accredited educational institutions and their foundations, or other educational institutions limiting appeals to the listed educational constituencies, can qualify. Check section 57-60(A)(1); a general educational mission alone is insufficient.']
 ,vaHealthEligible:['Does the entity meet Virginia’s qualifying health-facility or supporting nonprofit category?','The route includes recognized 501(c)(3) facilities licensed by Virginia health authorities, qualifying federal health centers, no-charge health providers and nonprofits solely supporting those facilities. See section 57-60(A)(7).']
 ,grantFundingOnly:['Are all contributions received from the grantmaker types you selected?','Include unsolicited gifts. Selecting grant applications only describes your requests; it does not by itself establish that all received funding comes from those grantmakers.']
 ,mdEducationMembers:['Are all donation requests limited to your educational members?', 'Maryland includes students, former students, their parents, present or former board members and staff of an accredited school, college or university. Public appeals do not meet this member-only route.']
 ,dcChurchEligible:['Are these appeals solely for a tax-exempt church, religious corporation or an entity it supervises and controls?','DC Code 44-1703(b) covers these specific entities, including qualifying religious education. A religious mission alone is insufficient.']
 ,okReligiousEligible:['Is the organization incorporated for religious purposes and actually conducting bona fide religious programs, or directly operated, supervised or controlled by a religious organization?','This follows the current Oklahoma Attorney General’s section 552.4 guidance. Confirm the incorporation, religious programs or direct religious control.']
 ,okEducationEligible:['Does the institution have faculty, regularly enrolled students and recognized degree courses, with appeals primarily to its students and families, alumni, faculty and trustees?','An associated 501(c)(3) must be authorized by and have an established identity with the qualifying institution. A general educational mission alone is insufficient.']
 ,kyReligiousPurpose:['Are the requests for the religious organization’s religious purposes?','Kentucky’s exclusion covers worship, services and propagation of faith, rather than another charity’s general civic fundraising.']
 ,kyEducationEligible:['Is this a publicly owned or nonprofit privately endowed school supervised by an appropriate public education authority, asking its educational constituencies or corporations for its established education program?','KRS 367.660(3) specifies alumni, faculty, students and their families, and corporations. It is not a blanket exemption for public campaigns.']
 ,kyFederalReturnRequired:['Is the organization required to file a Form 990-series annual return with the IRS?','Confirm your federal filing obligation. Newly formed organizations can need a notice of intent; uncertainty about 990-N treatment remains an agency question.']
 ,kyNewOrganization:['Is the organization newly formed and not yet required to have filed its first federal return?','Kentucky uses a notice of intent before covered solicitation for a newly formed organization. This question determines the initial route, not a renewal deadline.']
};
// Questions are shown only when the master assessment uses them.
Object.assign(QUESTIONS,{
 maReligiousHardship:['Does the charity hold property for religious purposes with a hardship separating it from other property, or need the Director to determine its religious use?','940 CMR 2.02(1)(b) permits a written request. The Director can approve or deny it; a religious mission or request alone does not grant the waiver.'],
 caFoundationOperatesInstitution:['Does this foundation itself operate the qualifying school or hospital as its primary activity?','Merely raising money for another institution does not make this legal entity the institution. Keep the organizing and operating evidence for the entity being assessed.'],
 ctNoPrimaryPaidSolicitation:['Is no person compensated primarily to conduct solicitations?','Connecticut uses primarily, rather than whether any employee ever assists with an appeal. Confirm the actual paid duties.'],
 dcMembershipOnly:['Are appeals exclusively among the existing membership of the soliciting organization?','The District excludes this specific audience. Public donation requests or giving someone membership because they donated do not establish this route.'],
 njSmallRoles:['Are all functions carried out by volunteers, members, officers or persons not compensated to solicit contributions?','Use the role condition in 45:17A-26(c). This is not a requirement that every non-fundraising employee be unpaid.'],
 njEducationEligible:['Does the institution have New Jersey-approved curriculum or limit appeals to its educational constituencies, with the required public financial report?','See 45:17A-26(b). An unrelated supporting foundation is not automatically the institution.'],
 njReligiousEligible:['Is this established for religious purposes or a qualifying religiously affiliated, operated, supervised or controlled charity?','Confirm the actual purpose and relationship in 45:17A-26(a).'],
 gaEducationEligible:['Is this an educational institution or an organization operated, supervised, controlled by or connected with a nonprofit educational institution?','Confirm the real institutional relationship. Federal 501(c)(3) recognition is already assumed by Head Start’s scope.'],
 gaReligiousEligible:['Does this entity conduct regular worship services, or qualify federally as a religious organization never required to file Form 990?','Georgia defines these as alternative religious routes; Form 990 alone does not decide the worship-service route.'],
 maReligiousCategory:['Does the organization fit one of the religious federal-return exclusions listed in 940 CMR 2.02(1)(a)?','Confirm Treasury Regulation 1.6033-2(g)(1)(i), (ii), (iv) or (vii). A general charitable federal filing exemption does not suffice.'],
 laEducationEligible:['Is this educational institution recognized or approved by Louisiana’s Department of Education or the appropriate state educational board?','Used when a professional solicitor makes the Louisiana campaign subject to registration.'],
 laHospitalEligible:['Is this a hospital organized under Louisiana law, or a qualifying voluntary health organization organized under Louisiana or federal law?','A hospital license elsewhere alone does not establish this Louisiana category.'],
 laReligiousEligible:['Does this institution meet the religious definition in Louisiana Administrative Code 16, Part III, section 515(A)?','Confirm the actual religious category in the agency’s exemption instructions.'],
 ilTrustCovered:['Does the entity hold property over $4,000 subject to Illinois’s charitable trust law?','Confirm the property threshold and Illinois connection. Solicitation relief alone does not answer this question.'],
 ctYoungOrganization:['Has the organization existed for fewer than three complete fiscal years?','Connecticut allows good-faith estimates for the years without history; actual completed-year totals must still be used.'],
 ctGoodFaithEstimates:['Are the figures for years without history documented good-faith estimates under Connecticut’s instructions?','Use actual completed-year records and documented annual estimates for the remaining years to form the three-year set. Blank years cannot be treated as zero.'],
 ohEducationSolicitation:['Does this institution limit appeals to its students, their families, alumni, faculty and trustees?','Ohio’s educational solicitation exemption is an audience test under 1716.03(A)(2).'],
 ohEducationTrust:['Does the institution have regular faculty, curriculum and regularly enrolled students?','This is Ohio’s separate educational trust exclusion. Solicitation audience relief alone is insufficient.'],
 ohReligiousEligible:['Is this organized and operated exclusively for religious purposes or a qualifying religiously controlled auxiliary?','The solicitation and trust laws have religious exclusions; confirm both definitions in the linked sources.'],
 kyFederalReturnRequired:['Must you file a federal Form 990, 990-EZ, 990-PF or 990-N?','Kentucky expressly lists 990-N as well as the full returns. This is an initial requirements question, not a filing calendar.'],
 kyNoFederalFiling:['Are you exempt from every federal annual return and 990-N notice requirement?','Confirm the actual federal exclusion. Having low receipts or filing a 990-N does not mean no filing obligation.'],
 miPublicFinancials:['Do you make the latest fiscal financial statement available to members and the public?','Michigan’s small solicitation route requires this; a new organization’s supporting-document exception is separate.'],
 miForeignNoAssets:['Is this entity organized outside Michigan and will it never hold charitable assets in Michigan?','Michigan’s trust exemption requires both facts. Include cash, savings, investment accounts and property; an out-of-state office alone is insufficient.'],
 ohNoPrimaryPaidSolicitation:['Is no person compensated primarily to solicit contributions?','Ohio’s small solicitation exemption uses this condition. Paid program staff alone do not disqualify it.'],
 ohNoTrustContact:['Is the entity organized outside Ohio, with no Ohio program services and no Ohio charitable assets?','All three facts are needed for the foreign-trust exclusion. Solicitation relief alone does not clear the charitable trust regime.'],
 akNoPaidEmployeesBoard:['Are all employees and board members unpaid?','Alaska’s small route requires this plus no compensated solicitor. This does not turn a national donor count into an online safe harbor.'],
 arSoleBenefit:['Does this entity solicit solely for qualifying exempt religious institutions, approved schools or licensed nonprofit hospitals?','Arkansas separately covers entities soliciting solely for exempt institutions. Confirm the supported institution’s eligibility.'],
 alEducationEligible:['Is this an educational institution, or its authorized and related foundation?','Confirm institutional identity and, for a foundation, the authorization and relationship. A general educational mission alone is insufficient.'],
 alHealthcareFoundation:['Is this entity itself a healthcare foundation?','A nonprofit hospital and its supporting healthcare foundation are different entities; Alabama lists the foundation category.'],
 ilEducationEligible:['Does this entity meet Illinois’s educational registration exemption?','Confirm State Board recognition, accepted accreditation, an established-identity foundation, or an institution limiting appeals to the listed educational constituencies; also satisfy the public-authority financial-report proviso where applicable under 225 ILCS 460/3(b)(1).'],
 ilOperatesSchool:['Is the entity organized for and actually engaged in operating a school?','Illinois’s separate trust exemption covers operation of schools or hospitals. Merely supporting an institution does not establish that exemption.'],
 ilTrustNotApplicable:['Can you document that Illinois’s separate charitable trust registration does not apply?','Confirm the trust’s location, assets and the $4,000 property scope in 760 ILCS 55. Do not infer this from solicitation exemption alone.'],
 ksEducationEligible:['Does this entity meet Kansas’s educational exemption and its public financial-report condition?','Qualifying accreditation, Board of Regents approval, established-identity foundations or educational-constituency appeals can qualify. The annual financial-report proviso remains separate from charity registration.'],
 ksHospitalEligible:['Is this a licensed medical care facility organized as a nonprofit corporation under Kansas law?','A licensed hospital incorporated elsewhere does not meet section 17-1762(n) on that fact alone.'],
 ksReligiousEligible:['Is the entity established for religious purposes or a qualifying religiously controlled or affiliated organization?','Confirm the purposes and actual affiliation, supervision or control described in 17-1762(k).'],
 meEducationEligible:['Is the curriculum approved by Maine’s Department of Education, directly or through an accreditor it recognizes?','A general educational mission or accreditation not recognized by the Department is insufficient.'],
 nonprofitHospital:['Is this entity itself a nonprofit, charitable hospital?','Confirm that it operates the hospital. A supporting foundation, health system or other affiliate is assessed separately.'],
 miEducationEligible:['Is this educational institution certified by Michigan’s State Board of Education?','CTS-03 says this generally applies to K–12. National university accreditation alone does not establish this route.'],
 miHospitalSupport:['Does this hospital-based foundation or auxiliary solicit solely for one or more licensed hospitals?','Michigan exempts this route from solicitation only. Charitable trust registration can still apply.'],
 mnEducationEligible:['Is the institution supervised by the listed Minnesota education authorities or accredited by a national or regional accrediting association?','See section 309.515(c). A supporting foundation is not automatically the institution itself.'],
 ndEducationEligible:['Is this an elementary or secondary school, or an organization soliciting funds for an institution of higher learning?','North Dakota’s definition separately excludes these entities; verify the actual institution and purpose.'],
 nmEducationEligible:['Is this a school or college with a defined curriculum, students, faculty and regular classes, or its qualifying auxiliary entity?','An auxiliary must actually support the institution, its curriculum, students, faculty, facilities or activities.'],
 nmReligiousEligible:['Is this organized for divine worship, religious teaching or another specific religious activity, or primarily to support such an organization?','Use New Mexico’s defined religious category, rather than an educational or charitable mission alone.'],
 nyEducationSolicitation:['Does the institution limit appeals to the listed educational constituencies, or file annual financial reports with the Regents or an equivalent out-of-state authority?','These are Article 7-A educational routes. They do not by themselves eliminate EPTL registration.'],
 nyEducationTrust:['Is this educational institution incorporated under New York Education Law or by special act?','This is the separate EPTL educational exemption. General accreditation alone is insufficient.'],
 riEducationEligible:['Does the institution have government-approved curriculum or qualifying Rhode Island educational recognition/accreditation?','See 5-53.1-3(a)(1); a foundation uses a separate exclusive-benefit route.'],
 riExclusiveBenefit:['Does this foundation or association exclusively benefit qualifying religious organizations, educational institutions or nonprofit charitable hospitals?','Verify the exclusive purpose and supported institutions under 5-53.1-3(a)(6).'],
 riReligiousEligible:['Is this a church, recognized denomination or qualifying religiously operated, supervised or controlled institution?','Use the categories in 5-53.1-3(a)(13); unrelated charitable activity is not automatically exempt.'],
 waChurchEligible:['Is the entity entitled to IRS tax exemption as a church?','Washington’s religious exception is for the federal church category, not every organization with a religious mission.'],
 orReligiousEligible:['Is this an organized church or group for divine worship, religious teaching or directly ancillary purposes?','Use Oregon’s definition in ORS 128.620(5), rather than any religiously inspired nonprofit.'],
 wvEducationEligible:['Is the curriculum approved by West Virginia’s State Board of Education or an accepted accreditor?','A supporting foundation or auxiliary must also be directly responsible to that institution.'],
 wvReligiousEligible:['Is this a qualifying church, synagogue, church association, religious order or integral church organization exempt from federal annual returns?','Section 29-19-6(5) requires the specified religious category and federal return exclusion.'],
 msEducationEligible:['Is this an accredited educational institution or its associated foundation?','Mississippi lists this category; confirm accreditation and any foundation relationship.'],
 msReligiousEligible:['Is this a bona fide, duly constituted religious institution meeting Mississippi’s definition?','A religious mission alone is insufficient. Integral affiliates must meet the state’s tax and support conditions.'],
 vaReligiousEligible:['Is this a church or a qualifying religious institution or integral affiliate under Virginia’s definition?','Confirm the religious category, tax exclusion and support conditions in section 57-48. A general civic mission is not automatically excluded.']
});
export const ELIGIBILITY_AMOUNTS={
 mdFiscalContributions:['Most recent fiscal year Maryland-defined nationwide contributions ($)','Exclude government grants. Apply Maryland’s public contribution definition; do not substitute all gross revenue or the rough annual estimate.'],
 ctAssessmentYearOne:['Connecticut annual figure 1: actual or documented projection ($)','Build the three-year set from completed-year actuals and documented good-faith annual estimates for years without history. Keep each figure’s basis with the CPC-54 evidence.'],
 ctAssessmentYearTwo:['Connecticut annual figure 2: actual or documented projection ($)','Use the same worldwide contribution definition. This is separate from the rough intake estimate.'],
 ctAssessmentYearThree:['Connecticut annual figure 3: actual or documented projection ($)','Two of the three figures must be below $50,000. Do not fabricate historical receipts for a year when the organization did not exist.'],
 coPersonsActual:['Persons contributing worldwide this fiscal year (whole persons)','Colorado’s separate ten-person exemption counts all contributors, not only Colorado or website donors. A contracted paid solicitor prevents this route.'],
 njFiscalContributions:['Most recent completed fiscal year nationwide gross contributions ($)','Apply New Jersey’s contribution definition, excluding government grants or contracts. Current-year crossings are checked separately; do not substitute a rough estimate.'],
 vaCalendarPriorTwo:['Nationwide contributions two calendar years ago ($)','Virginia requires each of the three preceding calendar years.'],vaCalendarPriorThree:['Nationwide contributions three calendar years ago ($)','Do not substitute a fiscal-year figure.'],
 miAdjustedActual:['Largest actual adjusted contribution total in any 12 months ($)','Nationwide; exclude government grants and restricted foundation grants.'],miAdjustedExpected:['Largest intended adjusted contribution total in any 12 months ($)','Use the same Michigan exclusions; do not substitute a single fiscal-year estimate.'],
 ohAdjustedRevenue:['Previous fiscal year Ohio adjusted gross revenue ($)','Nationwide gross revenue, excluding grants from government and organizations exempt under 501(c).'],
 scGrossActual:['Current fiscal year worldwide gross revenue so far ($)','All revenue, not donations alone. South Carolina Act 170 changed this basis in May 2026.'],scGrossExpected:['Expected full fiscal year worldwide gross revenue ($)','Include revenue solicited, collected, earned or received; do not use calendar contributions.'],
 akActual:['Actual annual nationwide contributions, excluding government grants ($)','Use Alaska’s statutory contribution basis.'],akExpected:['Intended annual nationwide contributions, excluding government grants ($)','A rough intake estimate does not establish eligibility.'],akDonorsActual:['Actual annual contributors (whole persons)','Count distinct persons, not payment transactions.'],akDonorsExpected:['Intended annual contributors (whole persons)','This is an exemption test, not an online nexus safe harbor.'],
 meActual:['Actual calendar year nationwide public contributions ($)','Use Maine’s contribution definition; government funds are excluded.'],meExpected:['Intended calendar year nationwide public contributions ($)','Use the same Maine definition.'],meDonorsActual:['Actual calendar year contributors (whole persons)','Count distinct persons.'],meDonorsExpected:['Intended calendar year contributors (whole persons)','Used only for Maine’s limited-contributor route.'],
 ksPersonsActual:['Actual persons solicited or contributing this period','Count all persons covered by the Kansas route, not only internet donors.'],ksPersonsExpected:['Intended persons solicited or contributing this period','No universal donor-count exemption is implied.']
};
const route=(checks,filing,action,url,regime=null)=>({checks,filing,action,url,regime});
const additionalRoute=(...args)=>({...route(...args),clarifiesCategory:true});
Object.assign(QUESTIONS,{
 akGamingPermit:['Does this organization hold a current Alaska charitable gaming permit?','A current permit under AS 05.15.100 is a separate charity-registration exclusion; a permit application is insufficient.'],
 nvRelatedOnly:['Are all appeals limited to relatives within the third degree of the organization’s officers, directors, trustees or executives?','Nevada’s restricted-audience route covers only the specified relatives. Public appeals do not qualify.'],
 nvNamedBeneficiary:['Are all appeals for a named person or immediate family, with every dollar used directly for their benefit?','No other solicitations may occur while relying on this Nevada route.'],
 nvAlumniOnly:['Is this an accredited institution’s alumni association appealing only to its established educational affiliates and permitted relatives?','A university or fundraising foundation is not automatically an alumni association under NRS 82A.015 and 82A.110.'],
 orEducationOnly:['Does this educational institution hold no Oregon property and solicit only its own alumni?','Both conditions are required for Oregon’s narrow educational exception.'],
 waTrustExempt:['Does the Washington trust qualify for an IRS religious, charitable-remainder or accredited public-education exclusion?','Confirm the separate trust category; a small solicitation exemption does not settle trust registration.'],
 paTaxExemption:['Does this Pennsylvania institution receive or claim a Pennsylvania property or sales tax exemption?','A separate annual purely-public-charity filing may apply even when solicitation registration is exempt.'],
 specialCategory:['Do your appeals involve a special veterans, law-enforcement or public-safety category?','Texas regulates specific categories and fundraising methods; ordinary charitable appeals are assessed separately.']
 ,ksCommunityFoundation:['Is this a publicly supported community foundation or trust serving a defined geographic area?','It must be a deductible 501(c)(3), publicly supported under 509(a)(1), rather than a private foundation; funds may support general or designated geographic-area charitable purposes.']
 ,ksLicensedCenter:['Is this a qualifying Kansas-licensed nonprofit medical facility or mental-health/disability center?','Includes nonprofit medical-care facilities organized under Kansas law, licensed community mental-health centers/clinics, and licensed intellectual-disability community centers and their recognized affiliates.']
 ,kyMemberOnly:['Are appeals only to genuine existing members and their families?','Membership must satisfy Kentucky’s definition, exist independently of donations, and not be offered as a way to avoid solicitation requirements.']
 ,kyStudentPta:['Is this local student-group or PTA fundraising approved by the educational institution’s administration?','The appeal must be for the group’s campus or connected activities, not a separate public campaign.']
 ,vaMembersOnly:['Are all appeals made by members solely to existing members of the organization?','Public appeals and membership offered solely in return for a gift do not establish this limited-audience route.']
 ,vaRegisteredAffiliate:['Do you have no Virginia office, make only the permitted outside-state appeals, and have a Virginia affiliate registered with VDACS?','All conditions are required: appeals from outside Virginia solely by email, telephone/telegraph, direct mail or national-media advertising; a chapter, branch or affiliate in Virginia must be registered.']
 ,vaLocalOnly:['Are Virginia appeals limited to five or fewer contiguous cities/counties, with each required local charity registration completed?','Count the localities and confirm registration under every applicable local solicitation ordinance. This is a separate local-area route.']
 ,vaLocalCosts:['Did payments outside those localities stay at or below 10% of last fiscal year gross receipts, after the permitted exclusions?','Exclude purchases of property or services used within the localities as section 57-60(B) specifies. An unverified estimate does not establish the limit.']
});
Object.assign(ELIGIBILITY_AMOUNTS,{
 nvPersonsSolicited:['Total people you will solicit this year, including those already asked','Count everyone asked or planned to be asked, including people who give nothing. Fewer than 15 is different from 15 donations.'],
 mnPersonsSolicited:['Persons solicited in the last completed accounting year','Minnesota’s private-foundation route allows no more than 100 persons; it is not an internet receipt test.'],
 mnTrustAssets:['Minnesota charitable trust assets ($)','A separate Chapter 501B review can apply at $25,000 or more.'],
 waTrustAssets:['Washington income-producing charitable trust assets ($)','Use assets invested under a charitable trust instrument, not total donations or every operating asset.'],
 paProgramRevenue:['Annual program-service revenue ($)','The separate Pennsylvania small-institution exception requires less than $5 million and contributions below $25,000.']
 ,flCurrentActual:['Florida-defined contributions received this fiscal year so far ($)','Actual receipts, not expected contributions. Reaching $50,000 ends the small-charity route.']
 ,njCurrentContributions:['Current-year nationwide gross contributions so far ($)','Crossing $10,000 can require registration within 30 days; do not wait until year end.']
});
export function institutionRoute(code,type,p={}){
 const edu=['school','university'].includes(type),foundation=type==='educationalFoundation';
 const hospital=type==='hospital',hospitalFoundation=type==='hospitalFoundation';
 const keep='Keep the qualifying institutional evidence and reassess if the category or appeals change.';
 if(code==='KS'&&(p.ksCommunityFoundation==='yes'||p.ksLicensedCenter==='yes'))return additionalRoute([p.ksCommunityFoundation==='yes'?'ksCommunityFoundation':'ksLicensedCenter'],'optional','The supplied category facts support the section 17-1762 exclusion. Retain IRS/category or Kansas licensing evidence; written agency confirmation may be requested.','https://www.kslegislature.gov/b2025_26/laws/017_000_0000_chapter/017_017_0000_article/017_017_0062_section/017_017_0062_k/');
 if(code==='KY'&&(p.kyMemberOnly==='yes'||p.kyStudentPta==='yes'))return additionalRoute([p.kyMemberOnly==='yes'?'kyMemberOnly':'kyStudentPta'],'none','The reported restricted member/family or approved local student/PTA appeals support a KRS 367.660 exclusion. Retain membership or school-administration approval evidence and reassess before broader appeals.','https://apps.legislature.ky.gov/law/Statutes/statute.aspx?id=35032');
 if(code==='VA'&&(p.vaMembersOnly==='yes'||p.vaRegisteredAffiliate==='yes'||p.vaLocalOnly==='yes'))return additionalRoute(p.vaMembersOnly==='yes'?['vaMembersOnly']:p.vaRegisteredAffiliate==='yes'?['vaRegisteredAffiliate']:['vaLocalOnly','vaLocalCosts'],'application','Submit Form 100 with the restricted-audience, registered-affiliate or local-area exemption evidence. Retain the agency’s letter and continue meeting the exact conditions; broader fundraising changes the route.','https://law.lis.virginia.gov/vacode/title57/chapter5/section57-60/');
 if(code==='NJ'&&(edu||type==='religious'))return route([edu?'njEducationEligible':'njReligiousEligible'],'verify','The statutory category supports exemption. Confirm the category-specific exemption-request procedure with Consumer Affairs before assuming no filing.','https://www.njconsumeraffairs.gov/charities/Pages/FAQ.aspx');
 if(code==='GA'&&(edu||foundation||type==='religious'))return route([type==='religious'?'gaReligiousEligible':'gaEducationEligible'],'none','No charity registration or exemption application is indicated under the qualifying category. '+keep,'https://sos.ga.gov/sites/default/files/2022-02/charity_org_info_release_revised_november_20185.pdf');
 if(code==='MA'&&type==='religious')return {...route(['maReligiousCategory'],'none','No charity registration is indicated under the federal-category waiver in 940 CMR 2.02(1)(a). Keep the specific federal exclusion evidence.','https://www.mass.gov/regulations/940-CMR-200-regulations-of-the-director-of-public-charities'),alternative:{...route(['maReligiousHardship'],'application','Submit a written religious-property waiver request to the Director under 940 CMR 2.02(1)(b). The Director decides whether to grant full or partial relief. Registration relief is not established until that decision.','https://www.mass.gov/regulations/940-CMR-200-regulations-of-the-director-of-public-charities'),discretionary:true}};
 if(code==='LA'&&(edu||hospital||type==='religious'))return route([type==='religious'?'laReligiousEligible':hospital?'laHospitalEligible':'laEducationEligible'],'application','When a professional solicitor triggers the charity program, submit Louisiana’s Charitable Exemption Form and supporting documents. Without that trigger, no charity registration or exemption application is indicated.','https://www.ag.state.la.us/Charity/');
 if(code==='AL'&&(edu||foundation||hospitalFoundation))return route([hospitalFoundation?'alHealthcareFoundation':'alEducationEligible'],'verify','The statutory category supports exemption. Alabama offers an exemption form; confirm whether the agency requires it for your category. A universal mandatory claim has not been established. '+keep,'https://www.alabamaag.gov/licensing-registration/charitable-organizations/');
 if(code==='AK'&&type==='religious')return route(['bonaFideReligious','religion990'],'optional','No solicitation registration is indicated under the qualifying religious exclusion. Alaska offers a one-time Notice of Exemption for notification. '+keep,'https://law.alaska.gov/department/civil/consumer/charityreg.html');
 if(code==='IL'&&(edu||foundation))return route(['ilEducationEligible'],'optional','The qualifying educational route removes solicitation registration under 225 ILCS 460/3(b)(1). Confirm with the Attorney General if written evidence is needed. The separate trust regime is evaluated below.','https://illinoisattorneygeneral.gov/Page-Attachments/ILCharitableOrganizLaws.pdf','IL');
 if(code==='KS'){
  const checks=edu||foundation?['ksEducationEligible']:hospital?['ksHospitalEligible']:type==='religious'?['ksReligiousEligible']:null;
  if(checks)return route(checks,'optional','No charity solicitation registration is indicated under the qualifying category. You may ask the Attorney General for confirmation; educational financial reports remain separate. '+keep,'https://www.kslegislature.gov/b2025_26/laws/017_000_0000_chapter/017_017_0000_article/017_017_0062_section/017_017_0062_k/');
 }
 if(code==='ME'){
  const checks=edu?['meEducationEligible']:hospital?['nonprofitHospital']:type==='religious'?['bonaFideReligious']:null;
  if(checks)return route(checks,'none','No charitable solicitation license or exemption application is indicated for the qualifying category. '+keep,type==='religious'?'https://www.mainelegislature.org/legis/statutes/9/title9sec5003.html':'https://www.legislature.maine.gov/legis/statutes/9/title9sec5006.html');
 }
 if(code==='MI'&&(edu||type==='religious'||hospitalFoundation))return route(edu?['miEducationEligible']:hospitalFoundation?['miHospitalSupport']:['bonaFideReligious','religion990'],'application','Submit CTS-03 with the specific institutional evidence. School and religious criteria can cover both regimes; hospital support relief covers solicitation only.','https://www.michigan.gov/consumerprotection/-/media/Project/Websites/AG/charities/registration-forms/Request-for-Exemption-CTS-3.pdf',hospitalFoundation?'MI':null);
 if(code==='MN'){
  const checks=edu?['mnEducationEligible']:type==='religious'?['bonaFideReligious','religion990']:null;
  if(checks)return route(checks,'application','Submit Minnesota’s Charitable Organization Exemption Form with the institutional evidence. Solicitation relief does not automatically clear charitable trust registration. '+keep,'https://www.ag.state.mn.us/Consumer/Handbooks/CharitiesLaws/CH2.asp');
 }
 if(code==='OH'&&(edu||type==='religious'))return route(edu?['ohEducationSolicitation']:['ohReligiousEligible'],'optional','The supplied facts support Ohio solicitation relief. Keep evidence and use the Attorney General’s system if claiming an exemption; the trust regime is assessed separately.','https://codes.ohio.gov/ohio-revised-code/section-1716.03',edu?'OH':null);
 if(code==='ND'){
  const checks=edu||foundation?['ndEducationEligible']:type==='religious'?['bonaFideReligious','religion990']:null;
  if(checks)return route(checks,'none','The qualifying category is excluded from North Dakota’s charitable organization definition. No charity solicitation registration is indicated. '+keep,'https://www.legis.nd.gov/cencode/t50c22.pdf');
 }
 if(code==='NM'){
  const checks=edu||foundation?['nmEducationEligible']:type==='religious'?['nmReligiousEligible']:null;
  if(checks)return route(checks,'none','No charity registration or exemption application is indicated under the qualifying statutory exclusion. '+keep,'https://nmag.gov/get-help/charities/');
 }
 if(code==='NH'&&type==='religious')return route(['bonaFideReligious'],'none','No charity registration is indicated under RSA 7:19 for qualifying religious organizations, integrated auxiliaries and church associations. '+keep,'https://gc.nh.gov/rsa/html/I/7/7-19.htm');
 if(code==='NV'&&type==='religious')return route(['bonaFideReligious'],'none','An organization established for and serving bona fide religious purposes is excluded from Nevada’s charitable organization definition. General exemption declarations under NRS 82A.110 are a different route. '+keep,'https://www.leg.state.nv.us/NRS/NRS-082A.html');
 if(code==='NY'&&edu)return route(['nyEducationSolicitation'],'optional','The supplied facts support Article 7-A educational relief. An unregistered exempt organization need not request approval unless it receives a failure-to-register notice; Schedule E is available for confirmation. EPTL is assessed separately.','https://ag.ny.gov/sites/default/files/regulatory-documents/Regs-F.pdf','NY');
 if(code==='OR'&&edu)return route(['orEducationOnly'],'none','No DOJ charity registration is indicated while the institution holds no Oregon property and solicits only its own alumni. '+keep,'https://www.doj.state.or.us/charitable-activities/starting-or-closing-a-charity/registering-a-new-charity/');
 if(code==='OR'&&type==='religious')return route(['orReligiousEligible'],'none','No charity registration is indicated under the qualifying religious exclusion. '+keep,'https://www.oregonlegislature.gov/bills_laws/ors/ors128.html');
 if(code==='RI'){
  const checks=edu?['riEducationEligible']:foundation||hospitalFoundation?['riExclusiveBenefit']:hospital?['nonprofitHospital']:type==='religious'?['riReligiousEligible']:null;
  if(checks)return route(checks,'none','No registration or exemption application is indicated under the self-executing exemption. Supply evidence if the director requests it. '+keep,'https://webserver.rilegislature.gov/Statutes/TITLE5/5-53.1/5-53.1-3.htm');
 }
 if(code==='WA'&&type==='religious')return route(['waChurchEligible'],'optional','No charity registration is indicated for an IRS church. Washington offers optional registration if you want the agency to answer public inquiries. '+keep,'https://www.sos.wa.gov/corporations-charities/frequently-asked-questions-faqs/charitable-organizations-frequently-asked-questions');
 if(code==='WV'){
  const checks=edu||foundation?foundation?['wvEducationEligible','foundationControl']:['wvEducationEligible']:hospital?['nonprofitHospital']:type==='religious'?['wvReligiousEligible']:null;
  if(checks)return route(checks,'application','Send the Secretary of State a letter describing the organization, fundraising practices and expected revenue for an exemption determination. '+keep,'https://sos.wv.gov/charities-frequently-asked-questions');
 }
 if(code==='MS'){
  const checks=edu||foundation?['msEducationEligible']:type==='religious'?['msReligiousEligible']:null;
  if(checks)return route(checks,type==='religious'?'none':'application',type==='religious'?'No registration or exemption notice is indicated for a qualifying religious institution. '+keep:'File the one-time online Notice of Exemption before solicitation with institutional and foundation evidence. '+keep,'https://charities.sos.ms.gov/online/portal/default/page/instructions/Portal.aspx');
 }
 if(code==='VA'&&type==='religious')return route(['vaReligiousEligible'],'none','No solicitation registration or Form 100 is indicated for an entity excluded by Virginia’s religious definition. '+keep,'https://law.lis.virginia.gov/vacode/title57/chapter5/section57-48/');
 if(code==='DC'&&['religious','school','university','educationalFoundation'].includes(type))return route(['dcChurchEligible'],'application','Before soliciting, file the IRS ruling letter and an affidavit that federal exemption remains in force under 16 DCMR 1303. No annual proof renewal is specified; continued federal exemption is required.','https://dcregs.dc.gov/Common/DCMR/SectionList.aspx?SectionNumber=16-1303');
 if(code==='OK'){
  if(type==='religious')return route(['okReligiousEligible'],'none','No charity solicitation registration is indicated while this religious exclusion applies. Retain incorporation, program and control evidence.','https://oklahoma.gov/oag/about/divisions/charity-enforcement.html');
  if(edu||foundation)return route(['okEducationEligible'],'none','No charity solicitation registration is indicated while the qualifying educational exclusion applies. Keep evidence of the institution, solicitation audience and any supporting organization’s authority and identity.','https://oklahoma.gov/oag/about/divisions/charity-enforcement.html');
 }
 if(code==='KY'){
  if(type==='religious')return route(['kyReligiousPurpose'],'none','No Kentucky solicitation return filing is indicated for these qualifying religious-purpose appeals. Keep evidence of the religious purpose; assess unrelated campaigns separately.','https://apps.legislature.ky.gov/law/Statutes/statute.aspx?id=35032');
  if(edu)return route(['kyEducationEligible'],'none','No Kentucky solicitation return filing is indicated under this educational solicitation exclusion while its institutional and audience conditions apply.','https://apps.legislature.ky.gov/law/Statutes/statute.aspx?id=35032');
 }
 if(code==='AL'&&type==='religious')return route(['bonaFideReligious'],'verify','The religious statutory exemption is supported. Alabama offers an exemption form; confirm any category-specific agency procedure rather than treating the form as universally mandatory.','https://www.alabamaag.gov/licensing-registration/charitable-organizations/');
 if(code==='NY'&&type==='religious')return route(['bonaFideReligious'],'none','No registration or reporting filing is indicated under the qualifying religious exclusions in Article 7-A and EPTL. Retain evidence of the religious organization category; review a separate affiliated entity under its own facts.','https://www.nysenate.gov/legislation/laws/EPT/8-1.4');
 if(code==='CO'&&type==='religious')return route(['coChurchEligible','religion990'],'none','No charity registration filing is indicated for a qualifying church category exempt from Form 990. Retain the federal church and return exclusion evidence.','https://www.sos.state.co.us/pubs/charities/FAQ/registration.html');
 if(code==='CA'&&['religious','school','university','hospital','educationalFoundation','hospitalFoundation'].includes(type))return route(foundation||hospitalFoundation?['caPrimaryInstitution','caFoundationOperatesInstitution']:['caPrimaryInstitution'],'optional','California exempts qualifying primary religious, educational and hospital institutions by law. A supporting foundation must qualify in its own right; affiliation alone is insufficient. A written exemption review with organizing documents and the IRS letter is available if confirmation is needed; do not submit it through the Online Filing Service.','https://oag.ca.gov/charities/initial-reg');
 if(code==='MI'&&type==='hospital')return route(['hospitalLicense','miHospitalEntity'],'application','Submit CTS-03 with the hospital license to confirm the licensed hospital exemption from both solicitation and charitable trust registration. A health system, affiliate or hospital foundation must be assessed separately.','https://www.michigan.gov/consumerprotection/charities/charitable-organizations');
 if(code==='MD'){
  if(edu)return route(['accreditation','mdEducationMembers','noSolicitor'],'none','No registration or disclosure filing is indicated under the qualifying member-only route. Keep accreditation and audience evidence and provide satisfactory exemption evidence if the Secretary of State requests it.','https://mgaleg.maryland.gov/mgawebsite/Laws/StatuteText?article=gbr&section=6-102');
  if(type==='religious')return route(['bonaFideReligious','noSolicitor'],'application','Send Maryland’s written religious exemption request with bylaws, organizing documents, IRS determination and mission information. A professional solicitor prevents this statutory exemption.','https://sos.maryland.gov/Charity/Pages/Registering-Charity.aspx');
 }
 if(code==='NC'){
  const checks=type==='religious'?['bonaFideReligious']:edu||foundation?['ncEducationEligible']:['hospital','hospitalFoundation'].includes(type)?['ncHospitalEligible']:null;
  if(checks)return route(checks,'optional','No solicitation license is indicated while the statutory exemption applies. You may request written exemption confirmation with supporting documents; keep eligibility evidence and reassess if your category or activities change.','https://www.sosnc.gov/divisions/charities/exemptions');
 }
 if(code==='VA'){
  const checks=edu||foundation?['vaEducationEligible']:['hospital','hospitalFoundation'].includes(type)?['vaHealthEligible']:null;
  if(checks)return route(checks,'application','Submit Virginia Form 100 and the required exemption-letter fee. Keep the agency determination; the exemption continues while the qualifying conditions remain true.','https://law.lis.virginia.gov/vacode/title57/chapter5/section57-60/');
 }
 if(code==='PA'){
  if(edu||foundation)return route(foundation?['paEducationApproval','foundationControl']:['paEducationApproval'],'optional','No solicitation registration filing is indicated if these criteria are met. Keep eligibility evidence. BCO-9 is available if you want agency approval of the exemption.','https://www.pa.gov/agencies/dos/programs/charities/excluded-or-exempt-organizations');
  if(['hospital','hospitalFoundation'].includes(type))return route(['paHospitalRegulated'],'optional','No solicitation registration filing is indicated if the regulated hospital route applies. BCO-9 is available for optional agency confirmation.','https://www.pa.gov/agencies/dos/programs/charities/information-for-charities/-charitable-organizations');
 }
 if(code==='CT'){
  const checks=type==='religious'?['bonaFideReligious']:edu?['accreditation']:type==='hospital'?['hospitalLicense']:['educationalFoundation','hospitalFoundation'].includes(type)?['ctSoleBenefit']:null;
  if(checks)return route(checks,'application','Submit Form CPC-54 to claim the exemption. Five years after approval and every five years thereafter, send a signed continued-eligibility letter updating officer/contact details under 21a-190k-3(d). This is not an annual exemption renewal.','https://portal.ct.gov/dcp/charities/general-information-on-the-connecticut-solicitation-of-charitable-funds-act');
 }
 if(code==='AR'){
  const checks=type==='religious'?['bonaFideReligious','paNoInurement']:edu?['accreditation']:type==='hospital'?['hospitalLicense']:foundation||hospitalFoundation?['arSoleBenefit']:null;
  if(checks)return route(checks,'application','Submit EX-01 with the IRS evidence and organizing documents for state review. Category eligibility alone does not complete the exemption filing.','https://www.sos.arkansas.gov/uploads/bcs/SoS_-CharitableRegistrationInArkansas_5.2025_.pdf');
 }
 if(code==='HI'){
  const checks=type==='religious'?['bonaFideReligious','religion990']:edu?['hiEducationEligible']:foundation?['hiFoundationEligible']:type==='hospital'?['hospitalLicense']:null;
  if(checks)return {...route(checks,'application','Apply through Hawaii’s charity exemption system and obtain the Attorney General’s approval before relying on the exemption. Retain the determination.','https://ag.hawaii.gov/tax/files/2019/10/Frequently-Asked-Questions.pdf'),approvalRequired:true};
 }
 if(code==='FL'){
  const checks=type==='religious'?['flReligiousEligible']:edu||foundation?['flEducationEligible']:null;
  if(checks)return route(checks,'none','No FDACS solicitation registration or exemption application is required for a qualifying religious or educational institution. Keep evidence of the statutory category.','https://www.fdacs.gov/Consumer-Resources/Charities/Charities-FAQ/Do-all-fundraising-organizations-have-to-register-with-the-state');
 }
 if(code==='TN'){
  const checks=type==='religious'?['tnReligiousEligible']:edu||foundation?['tnEducationEligible']:type==='hospital'?['tnHospitalRegulated']:null;
  if(checks)return route(checks,'none','No solicitation registration or small organization exemption statement is indicated under this institutional route. Retain evidence of the defined category and section 48-101-502 exemption.','https://sos-tn-gov-files.tnsosfiles.com/forms/Charitable%20Solicitations%20Act.pdf');
 }
 if(code==='WI'){
  const checks=type==='religious'?['religion990']:edu||foundation?['wiEducationEligible']:null;
  if(checks)return route(checks,'none','No charitable solicitation registration filing is indicated while the statutory exemption applies. Keep supporting eligibility evidence.','https://dfi.wi.gov/Pages/BusinessServices/CharitableProfessionalOrganizations/CharitableOrganizationsFAQ.aspx');
 }
 if(code==='SC'){
  if(type==='religious')return route(['scReligiousEligible'],'none','No charitable solicitation registration or annual exemption application is indicated for a qualifying excluded religious entity. This is the section 33-56-20 exclusion, not a section 33-56-50 exemption.','https://www.scstatehouse.gov/code/t33c056.php');
  if(edu)return route(['scEducationAudience','noExternal'],'annual','Submit the annual Application for Registration Exemption while eligible. Educational eligibility does not eliminate that annual application.','https://www.sos.sc.gov/online-filings/charities-pfrs-and-raffles/charities');
 }
 return null;
}
export const FILING_LABELS={none:'Exemption appears applicable · no filing',optional:'Exemption appears applicable · confirmation optional',application:'Submit an exemption claim',annual:'Submit an annual exemption application',simplified:'Submit annual small charity paperwork',verify:'Confirm the exemption filing procedure'};
export const SMALL_FILINGS={AL:'verify',AR:'application',CO:'none',CT:'application',FL:'simplified',GA:'none',HI:'application',MN:'application',NC:'optional',PA:'optional',RI:'none',SC:'annual',TN:'annual',WA:'none',WI:'none',MD:'simplified',VA:'application',WV:'application',KS:'optional',MI:'application',OH:'none',AK:'optional',ME:'none',NJ:'verify',DC:'verify'};
// Taxonomies checked against the linked primary sources. Absence of a category
// route means ordinary registration/small rules apply, not generic uncertainty.
export const VERIFIED_CATEGORY_STATES=new Set(['AL','AK','AR','CA','CO','GA','IL','KS','ME','MD','MI','MN','MS','MA','NV','NH','NJ','NM','ND','NY','OH','OR','RI','SC','VA','WA','WV']);
