// Conditional next steps, not independent registration decisions. The master
// assessment attaches these to its results; provider businesses are out of scope.
export function nextSteps(p,r){
 const steps=[];
 const add=(title,text,url)=>steps.push({title,text,url});
 const active=r.status!=='outside';
 if(!active){if(r.code==='FL'&&p.online==='yes')add('Confirm Florida’s connection','An untargeted out-of-state donation page does not by itself establish Florida targeting or blanket clearance. Confirm actual Florida appeals, receipts, business or other connections before assigning a filing route.','https://www.fdacs.gov/business-services/solicitation-of-contributions');return steps;}
 if(r.code==='CT'&&r.status==='exemption')add('Keep exemption eligibility current','CPC-54 is the initial claim. Five years after approval and every five years thereafter, submit a signed letter confirming continued eligibility and updating officers/contact details. There is no annual exemption renewal.','https://eregulations.ct.gov/eRegsPortal/Search/getDocument?guid=%7BA0A84A6D-0500-CCCF-8086-851A96A08902%7D');
 if(r.code==='IL'&&r.status==='required')add('Initial filing versus report relief','Illinois’s religious and no-more-than-$15,000 routes in 225 ILCS 460/3(a) concern report relief after an initial registration statement. They do not remove initial registration. Separately check charitable trust property in excess of $4,000 and any institutional trust exclusion.','https://illinoisattorneygeneral.gov/Page-Attachments/ILCharitableOrganizLaws.pdf');
 if(r.code==='PA'&&(p.base==='PA'||(p.operations||[]).includes('PA'))){
  const known=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))&&Number(v)>=0;
  const religious=p.type==='religious'&&p.religion990==='yes',small=known(p.fiscalActual)&&Number(p.fiscalActual)<25000&&known(p.paProgramRevenue)&&Number(p.paProgramRevenue)<5000000;
  const outsideSmall=known(p.fiscalActual)&&Number(p.fiscalActual)>=25000||known(p.paProgramRevenue)&&Number(p.paProgramRevenue)>=5000000;
  add('Separate Pennsylvania public-charity filing',p.paTaxExemption==='no'?'No Pennsylvania property or sales tax exemption was reported; this separate tax-linked annual filing is not established.':religious?'Your religious annual-return exclusion can also support the purely-public-charity filing exception; retain the religious and federal-return evidence.':small?'The supplied contributions below $25,000 and program revenue below $5 million support the separate small-institution exception; confirm the tax-linked scope.':p.paTaxExemption==='yes'&&p.type!=='religious'&&outsideSmall?'The separate tax-linked annual purely-public-charity filing is indicated; solicitation relief does not remove it. Manage the annual filing in CC Aurora.':'If you receive or claim Pennsylvania property or sales tax exemption, review the separate annual purely-public-charity report. Solicitation relief alone does not remove it. Exceptions include qualifying religious no-990 institutions, or contributions below $25,000 AND program revenue below $5 million.','https://www.pa.gov/agencies/dos/programs/charities/information-for-charities/purely-public-charities');
 }
 if(r.status==='required'||r.filing&&['application','annual','simplified'].includes(r.filing))
  add('Prepare the initial filing','Use the agency’s current form or portal. Gather the IRS determination letter, organizing documents and supporting eligibility evidence. A Unified Registration Statement does not replace state-specific requirements.',r.sources[0]?.url);
 if((p.operations||[]).includes(r.code)||r.code===p.base)
  add('Keep entity filings separate','Check corporate formation or foreign qualification for your operations. A charity registration does not itself create authority to do business. A corporate registered agent and a charity service-of-process contact serve different filings.',r.sources[0]?.url);
 if(r.code==='CO'&&r.status==='required')add('Colorado filing prerequisite','If incorporated outside Colorado, first file a Statement of Foreign Entity Authority in the business system, then create the charity account and file the charitable registration. Confirm the corporate registered agent for that separate entity filing.','https://www.sos.state.co.us/pubs/charities/FAQ/registration.html');
 if(r.code==='MI'&&r.status==='required')add('Michigan service-of-process contact','Michigan’s charity filing has a resident-agent requirement, including when using the Unified Registration Statement. Confirm that appointment on the current form; it is separate from any corporate qualification decision.','https://www.michigan.gov/consumerprotection/charities/charitable-organizations');
 if(r.status==='required')add('Wait for required authorization','Submitting a form is not proof of registration or permission to fundraise. Check the agency’s approval and effective-date rules before starting covered appeals.',r.sources[0]?.url);
 if(r.status==='required'||(p.registered||[]).includes(r.code))
  add('Manage ongoing filings in CC Aurora','Use CC Aurora for current registration standing, filing dates, renewals, extensions, audit requirements, fees and historical filing management. Head Start identifies the initial registration or exemption route.');
 if((p.target||[]).includes(r.code)||p.receipts?.[r.code]?.emailAppeals==='yes'||r.code===p.base&&p.homeOnly!=='none')
  add('Review your appeal materials','Check this state’s disclosure wording for websites, email, printed appeals, receipts and paid campaigns. Registration is not a state endorsement. Do not copy one state’s wording across all appeals.',r.code==='NC'?'https://www.ncleg.gov/EnactedLegislation/Statutes/HTML/ByChapter/Chapter_131F.html':r.sources[0]?.url);
 if(r.code==='FL'&&(r.status==='required'||r.filing==='simplified'||(p.registered||[]).includes('FL')))
  add('Florida disclosure placement','Use the exact statutory notice, including the Division’s toll-free number and website, on solicitations, confirmations, receipts and reminders. On a fundraising website, display it on pages with a mailing address for gifts, a phone number for processing gifts, or online checkout. Registered charities must also display their registration number on the specified printed and written materials. See section 496.411(3) and (6).','https://www.flsenate.gov/Laws/Statutes/2026/496.411');
 if(r.status==='required')add('Public documents do not replace filing','Publishing Form 990, the exemption application or a Unified Registration Statement does not fulfill state registration. Complete the agency’s actual filing and required attachments.',r.sources[0]?.url);
 if(p.pastSolicitation==='yes')
  add('Review earlier activity in CC Aurora','Past fundraising was reported. Use CC Aurora to assess historical filing duties; this prospective requirements screen does not resolve earlier activity.');
 if(['solicitor','consultant','coVenturer'].some(k=>p[k]==='yes')||p.onlineMethod==='platform')
  add('Check the fundraising arrangement','Confirm who requests gifts, who holds or controls the funds, compensation and the written contract. Check applicable provider registration, campaign notices and contract filings. A platform or consultant does not automatically take over your nonprofit’s filing duties.',r.code==='CA'?'https://oag.ca.gov/charities/pf':r.sources[0]?.url);
 if(p.onlineMethod==='platform'&&r.code==='CA')
  add('California platform eligibility','Ask the platform to verify eligible-charity status, required standing and consent before it lists or pays your charity. Receiving donations through a platform does not automatically make your nonprofit a platform charity.','https://oag.ca.gov/charities/pl');
 if(p.onlineMethod==='platform'&&r.code==='HI')
  add('Hawaii platform rules','Hawaii’s platform registration law took effect July 1, 2026. Confirm the platform’s registration and applicable charity eligibility requirements before the campaign; this is separate from your nonprofit’s own registration or exemption.','https://data.capitol.hawaii.gov/hrscurrent/Vol10_Ch0436-0474/HRS0467B/HRS_0467B-0002_0003.htm');
 return steps;
}
