// Research snapshot: 2026-10-03. Sources are authoritative agencies or statutes.
// A profile is a screening rule, never evidence of an organization's current standing.
export const VERSION = '0.11.0-dev';
export const REVIEW_DATE = '2026-10-03';
const rows = [
['AL','Alabama','solicit','https://www.alabamaag.gov/licensing-registration/charitable-organizations/','Attorney General · charitable organizations','religious,school,university,hospital,foundation,membership','Religious, educational and certain other categories may qualify. Review the exact statutory category and exemption portal.','Small exemption: actual and intended contributions no more than $25,000; fundraising must be unpaid.'],
['AK','Alaska','solicit','https://law.alaska.gov/department/civil/consumer/charityreg.html','Department of Law · registration','religious,school,university,membership','Religious, educational and certain membership organizations have exclusions. Confirm eligibility.','Small organization and limited donor exemptions have additional conditions; not automated in this version.'],
['AZ','Arizona','veterans','https://azsos.gov/business/other-services/veterans-charities-organizations','Secretary of State · veterans charities','','Ordinary charitable solicitation has no general Secretary of State registration. Veterans fundraising has a separate program.','Veterans status must be assessed before a negative result.'],
['AR','Arkansas','solicit','https://www.sos.arkansas.gov/uploads/bcs/SoS_-CharitableRegistrationInArkansas_5.2025_.pdf','Secretary of State · registration guide','religious,school,university,hospital','Exempt organizations submit EX-01 verification. School approval and hospital licensing matter.','Small exemption: no more than $50,000 actual or intended in a calendar year; all functions unpaid and no officer or member income.'],
['CA','California','assets','https://oag.ca.gov/charities/initial-reg','Attorney General · initial registration','religious,school,university,hospital','Organizations primarily religious, educational or hospital based may be excluded; case by case review is available.','Assets, activities and solicitation can trigger registration. Generally file within 30 days after initial receipt of charitable assets; no general small dollar exemption.'],
['CO','Colorado','solicit','https://www.sos.state.co.us/CCR/GenerateRulePdf.do?fileName=8+CCR+1505-9&ruleVersionId=5762','Secretary of State · 8 CCR 1505-9','religious,school,university,membership','Review statutory exemptions under C.R.S. 6-16-104(6), including religious and educational qualifications.','Internet Rule 10: targeting, domicile, 50 online contributions OR the lesser of $25,000 or 1% of total contributions. Small organization exemption requires a separate statutory check.'],
['CT','Connecticut','solicit','https://portal.ct.gov/dcp/charities/general-information-on-the-connecticut-solicitation-of-charitable-funds-act','Consumer Protection · solicitation act','religious,school,university,hospital,membership','An exemption claim uses the agency exemption process; accredited education and nonprofit hospital criteria matter.','Small exemption: less than $50,000 and no compensation primarily for solicitation.'],
['DE','Delaware','none','https://www.irs.gov/charities-non-profits/delaware','IRS · Delaware state requirements','','No general charitable solicitation registration statute is identified. Private foundation and other entity filings remain separate.','This assessment does not cover federal or corporate annual filings.'],
['DC','District of Columbia','pending','https://code.dccouncil.gov/us/dc/council/code/titles/44/chapters/17/index.full.html','DC Code · charitable solicitation','religious','DC licensing and exemptions require a fact specific review.','This prototype links the statute but does not automate DC licensing thresholds.'],
['FL','Florida','solicit','https://www.fdacs.gov/Business-Services/Solicitation-of-Contributions','FDACS · solicitation of contributions','religious,school,university','Religious and qualifying educational institutions are excluded. Small charities use an annual small organization application, not a filing free exemption.','Small application: less than $50,000 in the preceding fiscal year, volunteer fundraising, no officer or member income, and no professional solicitor, consultant or commercial co-venturer.'],
['GA','Georgia','solicit','https://sos.ga.gov/sites/default/files/2022-02/charity_org_info_release_revised_november_20185.pdf','Secretary of State · charity guidance','religious,school,university','Review religious and educational definitions. Retain documentation for any statutory exemption.','Small exemption: less than $25,000 in both previous and current calendar years and no paid solicitor.'],
['HI','Hawaii','solicit','https://ag.hawaii.gov/tax/files/2019/10/Frequently-Asked-Questions.pdf','Attorney General · charity FAQ','religious,school,university,hospital','Exemption application available for qualifying religious, accredited educational and licensed nonprofit hospital organizations.','Applications to government or other 501(c)(3) grantmakers are excluded from solicitation; these grants are also excluded from contribution totals. Guidance document dated 2019.'],
['ID','Idaho','none','https://www.nasconet.org/survey-map','NASCO · state charities registration survey','','Idaho has no general charitable solicitation registration requirement. This matches the supplied booklet and the current NASCO survey.','Other entity, tax, local solicitation or special activity requirements are outside this general registration conclusion.'],
['IL','Illinois','assets','https://illinoisattorneygeneral.gov/Consumer-Protection/Charities/Building-Better-Charities/Forming-Charitable-Organizations/','Attorney General · forming charities','religious,school,university','An educational annual reporting exemption does not itself eliminate initial registration. Religious exclusions require a separate review.','Solicitation and holding charitable assets are separate triggers. Reporting relief and initial registration must be assessed separately.'],
['IN','Indiana','paidOnly','https://secure.in.gov/attorneygeneral/consumer-protection-division/charities-and-donors/charitable-fundraising/','Attorney General · fundraising','','No general charity registration program is identified; professional solicitor registration and campaign obligations are separate.','Paid fundraising triggers an additional review, not an automatic charity registration conclusion.'],
['IA','Iowa','paidOnly','https://www.iowaattorneygeneral.gov/for-businesses/charities-nonprofits-fundraising-information','Attorney General · charity information','','General charity solicitation registration is not the core filing; professional fundraiser and charitable trust duties require separate assessment.','Charitable assets or private foundation activity are referred for review.'],
['KS','Kansas','solicit','https://www.kslegislature.gov/b2023_24/laws/017_000_0000_chapter/017_017_0000_article/017_017_0062_section/017_017_0062_k/','Kansas Legislature · section 17-1762','religious,school,university,hospital,foundation,membership','Statutory exclusions include qualifying education, religious and Kansas licensed medical organizations.','Small dollar and limited persons exemptions have distinct conditions; confirm with the Attorney General.'],
['KY','Kentucky','kentucky','https://www.ag.ky.gov/Resources/Consumer-Resources/charity/Pages/faq.aspx','Attorney General · charities FAQ','religious,school,university','Kentucky uses a Form 990 submission framework rather than a conventional application.','The federal return requirement and KRS 367.660 exemptions must be confirmed, including 990-N treatment.'],
['LA','Louisiana','louisiana','https://www.ag.state.la.us/Charity/','Attorney General · charities','','Organizations using professional solicitors have an annual registration obligation before solicitation.','A paid employee or consultant can require a definition review; do not assume all paid roles are identical.'],
['ME','Maine','solicit','https://www.legislature.maine.gov/legis/statutes/9/title9sec5006.html','Maine Legislature · section 5006','religious,school,university,hospital,membership','Exemption eligibility and required statement must be confirmed under section 5006.','Dollar and limited donor exemptions are not automated; professional solicitor use and private benefit matter.'],
['MD','Maryland','solicit','https://sos.maryland.gov/Charity/Pages/Registering-Charity.aspx','Secretary of State · registering a charity','religious','Small organizations can still have an Exempt Organization Fundraising Notice obligation.','Below $25,000 is not a blanket no filing result. Religious exemption requests require supporting evidence.'],
['MA','Massachusetts','assets','https://www.mass.gov/info-details/frequently-asked-questions-about-charitable-organizations','Attorney General · charity FAQ','religious','Religious exclusions require eligibility review; charity registration and public solicitation certificate duties differ.','Assets and conducting charitable activity can create obligations apart from appeals. No general small dollar exclusion is automated.'],
['MI','Michigan','assets','https://www.michigan.gov/consumerprotection/about/frequently-asked-questions/faq-categories-folder/charity-pfr-ps-questions','Attorney General · charity FAQ','religious,school,university','Separate solicitation licensing and charitable assets registration. School exclusions can depend on Michigan approval.','A small solicitation exclusion does not settle the charitable assets registration question.'],
['MN','Minnesota','solicit','https://www.revisor.mn.gov/statutes/cite/309.515','Minnesota Legislature · section 309.515','religious,school,university,membership','An exemption notice and supporting facts may be needed; private foundation trust rules are separate.','Small exemption: actual and expected contributions no more than $25,000, all functions unpaid, no officer or member income, and no professional fundraiser.'],
['MS','Mississippi','solicit','https://sos.ms.gov/sites/default/files/charities/MS%20Charities%20Act%20Rules%20-%20September%202025.pdf','Secretary of State · September 2025 rules','religious,school,university,hospital','Check exemption certificate eligibility and changes under Rule 2.07.','Rule 2.08: local bank or address, paid targeting, or online receipts or intended receipts at least $25,000 OR at least 25 distinct resident donors.'],
['MO','Missouri','exempt501','https://ago.mo.gov/get-help/programs-services-from-a-z/charity/for-nonprofits/registration-faqs/','Attorney General · registration FAQ','','Recognized 501(c)(3) organizations are exempt from the charitable registration program.','An IRS determination letter can be supplied for confirmation; other entity duties remain separate.'],
['MT','Montana','none','https://www.nasconet.org/survey-map','NASCO · state charities registration survey','','Montana has no general charitable solicitation registration requirement. This matches the supplied booklet and the current NASCO survey.','Montana entity annual reporting is separate. Fundraising in another state is assessed under that state’s rules.'],
['NE','Nebraska','paidOnly','https://sos.nebraska.gov/licensing/information-charitable-solicitors','Secretary of State · charitable solicitors','','Charitable organizations no longer register under the solicitor program. Paid solicitor requirements remain.','Review professional fundraising separately.'],
['NV','Nevada','solicit','https://nvsos.gov/index.aspx?page=1344','Secretary of State · nonprofit solicitation','religious','Charitable solicitation statement and disclosure obligations differ. Churches and limited person appeals have exclusions.','An exemption statement may still be filed. Fewer than 15 persons and entity registration are not automated here.'],
['NH','New Hampshire','assets','https://gc.nh.gov/rules/state_agencies/jus400.html','NH administrative rules · Jus 400','religious','Religious exclusions require review. Foreign organizations are assessed for reasonable contacts; domestic organizations have trust unit obligations.','Reasonable contacts include operations, targeting, or repeated, ongoing or substantial receipts. No numeric online safe harbor is assumed.'],
['NJ','New Jersey','assets','https://www.njconsumeraffairs.gov/charities/pages/charities-registration-information.aspx','Consumer Affairs · registration','religious,school,university','Operating, being based or soliciting in New Jersey can matter. Verify statutory exemptions.','Short form registration is not an exemption. Small dollar and paid fundraiser definitions require a separate review.'],
['NM','New Mexico','assets','https://www.nmag.gov/get-help/charities/','Department of Justice · charities','religious,school,university','Religious and educational exclusions have defined conditions.','Existing, operating or soliciting can create obligations; no small dollar exemption is automated.'],
['NY','New York','assets','https://ag.ny.gov/resources/government-organizations/charities-nonprofits-fundraisers/charities-registration','Attorney General · registration','religious,school,university','Article 7-A solicitation and EPTL trust registration are separate. Exemptions can apply to one and not the other.','Foundation and government grants can count as solicitation. Small solicitation relief does not settle trust registration.'],
['NC','North Carolina','solicit','https://www.sosnc.gov/divisions/charities/exemptions','Secretary of State · exemptions','religious,school,university,hospital,foundation','Written exemption requests require supporting evidence; hospital licensing and educational accreditation matter.','Small exemption: less than $50,000 in a calendar year with no compensation to officers, trustees, organizers, incorporators, fundraisers or solicitors.'],
['ND','North Dakota','solicit','https://www.sos.nd.gov/business/nonprofit-services/charitable-organizations','Secretary of State · charitable organizations','religious,school,university','Qualifying schools, higher education appeals and religious organizations exempt from federal annual returns are excluded.','Charity registration and nonprofit entity annual reports are separate. No general small dollar exclusion is automated.'],
['OH','Ohio','assets','https://charitable.ohioago.gov/Charity-Registration','Attorney General · charity registration','religious,school,university','Charitable trust and solicitation rules must be assessed separately; submit exemption evidence through the state portal.','A small organization or educational solicitation exemption does not necessarily resolve trust duties.'],
['OK','Oklahoma','pending','https://www.sos.ok.gov/charity/Default.aspx','Secretary of State · charitable organizations','religious,school,university','Current threshold and exemption verification remain a research task.','Ordinary solicitation is a registration screening issue; no exemption or clearance is automated.'],
['OR','Oregon','assets','https://www.doj.state.or.us/charitable-activities/starting-or-closing-a-charity/registering-a-new-charity/','Department of Justice · registering a charity','religious','Foreign organizations can be covered by solicitation, assets or business activity.','No general small dollar exemption is automated. Review religious eligibility independently.'],
['PA','Pennsylvania','solicit','https://www.pa.gov/agencies/dos/programs/charities/excluded-or-exempt-organizations','Department of State · exclusions and exemptions','religious,school,university,hospital,veterans,membership','Hospital licensing, school approval and other category conditions must be verified. Purely public charity filings can be separate.','Small exemption: gross national contributions no more than $25,000 with no compensated solicitation.'],
['RI','Rhode Island','solicit','https://dbr.ri.gov/banking-securities-and-charitable-organizations/securities-and-charities/charitable-organizations','Business Regulation · charities','religious,school,university,hospital','Statutory exemptions are self executing; the agency does not grant or approve exemption requests.','Register if actual or intended fiscal year contributions exceed $25,000 or a professional fundraiser is used.'],
['SC','South Carolina','solicit','https://sos.sc.gov/online-filings/charities-pfrs-and-raffles/charities','Secretary of State · charities','religious,school,university,membership','An annual exemption filing may be required. Review institution criteria.','The small organization exemption has a $20,000 ceiling and individual compensation conditions; not automated.'],
['SD','South Dakota','paidOnly','https://consumer.sd.gov/fastfacts/charity.aspx','Consumer Protection · charities','','No general charity registration program is identified. Paid telephone solicitation has separate obligations.','Paid fundraising is referred for campaign review.'],
['TN','Tennessee','solicit','https://sos-tn-gov-files.tnsosfiles.com/forms/Charitable%20Solicitations%20Act.pdf','Secretary of State · solicitation act','religious,school,university,hospital','Qualifying religious, educational and Tennessee regulated healthcare organizations can be exempt.','Small exemption: actual and intended gross public contributions no more than $50,000 in a fiscal year; annual exemption request. Current online rule text requires further verification.'],
['TX','Texas','texas','https://www.texasattorneygeneral.gov/divisions/charitable-trusts/registration-and-filings','Attorney General · registration and filings','','Most charities have no general solicitation filing. Veterans, law enforcement, public safety and private foundation filings require separate review.','Special purpose telephone appeals must be assessed before a negative result.'],
['UT','Utah','utah','https://commerce.utah.gov/dcp/for-businesses/charities/','Commerce · charities','','DCP charity licensing ended in 2024. Entity registration and annual IRS return submissions through the corporations division can still apply.','Do not interpret the end of DCP licensing as no state obligations.'],
['VT','Vermont','paidOnly','https://ago.vermont.gov/attorney-generals-office-divisions-and-units/consumer-protection/charities-and-paid-fundraisers','Attorney General · paid fundraisers','','No general charity registration program is identified; paid fundraiser notices and requirements remain separate.','Review professional fundraising contracts and campaigns.'],
['VA','Virginia','solicit','https://www.vdacs.virginia.gov/food-charitable-solicitation.shtml','VDACS · charitable solicitation','religious,school,university,hospital,membership','Exclusions and exemption applications differ. Verify Form 100 and statutory eligibility.','Small dollar and limited donor exemptions are not automated.'],
['WA','Washington','solicit','https://www.sos.wa.gov/corporations-charities/frequently-asked-questions-faqs/charitable-organizations-frequently-asked-questions','Secretary of State · charity FAQ','religious','Church eligibility requires IRS church status, not merely a religious mission.','Small exemption: less than $50,000 with all activities conducted without compensation.'],
['WV','West Virginia','solicit','https://sos.wv.gov/FormSearch/Business/Documents/ExemptChar.pdf','Secretary of State · exemption form','religious,school,university,hospital','Exemption form and category conditions must be verified.','Calendar year small organization relief includes compensation conditions; not automated.'],
['WI','Wisconsin','solicit','https://dfi.wi.gov/Pages/BusinessServices/CharitableProfessionalOrganizations/CharitableOrganizationsFAQ.aspx','DFI · charitable organizations FAQ','religious,school,university','Religious federal return exclusions, approved schools and specified member appeals can qualify.','Online nexus: Wisconsin domicile or targeting, or at least 50 contributions AND more than $25,000 from residents in a fiscal year. Small exemption has a $25,000 ceiling and all unpaid functions.'],
['WY','Wyoming','none','https://sos.wyo.gov/faqs.aspx?root=BUS','Secretary of State · business FAQ','','No general state charitable solicitation registration requirement is identified.','Foreign entity qualification and other corporate filings are separate.']
];
export const STATES=rows.map(([code,name,mode,url,source,categories,note,nuance])=>({code,name,mode,sources:[{url,title:source}],categories:categories?categories.split(','):[],note,nuance,reviewed:REVIEW_DATE,coverage:mode==='pending'?'Incomplete':'Core framework checked; exceptions screened'}));
const extra={
  CO:'https://www.sos.state.co.us/pubs/info_center/laws/Title6/Title6Article16.html',
  MS:'https://online.sos.ms.gov/online/portal/ch/page/instructions/Portal.aspx',
  MN:'https://www.ag.state.mn.us/Consumer/Handbooks/CharitiesLaws/CH2.asp',
  PA:'https://www.pa.gov/agencies/dos/programs/charities/information-for-charities/purely-public-charities',
  FL:'https://www.fdacs.gov/Consumer-Resources/Charities/Charities-FAQ/Do-all-fundraising-organizations-have-to-register-with-the-state'
};
for(const s of STATES) if(extra[s.code])s.sources.push({url:extra[s.code],title:'Agency or statutory companion guidance'});
// Deliberately limited automation. Untested criteria stay in the review branch.
export const SMALL={
 AL:{amount:25000,inclusive:true,period:'fiscal',conditions:['unpaidFundraising'],action:'Confirm the statutory exemption and whether the agency expects an exemption claim.'},
 AR:{amount:50000,inclusive:true,period:'calendar',conditions:['allUnpaid','noPrivateBenefit'],action:'Submit EX-01 with supporting eligibility evidence.'},
 CO:{amount:25000,inclusive:true,period:'coGross',conditions:['noSolicitor'],action:'Keep evidence of actual and intended adjusted gross revenue of no more than $25,000 and no contracted paid solicitor. Colorado excludes government and 501(c)(3) grants from this revenue test; this is not a contribution-only test.'},
 CT:{amount:50000,inclusive:false,period:'threeFiscal',conditions:['ctNoPrimaryPaidSolicitation'],action:'Submit the one time CPC-54 exemption claim. Connecticut uses worldwide contributions below $50,000 in two of the last three years, or the documented good-faith annual estimates permitted for a younger organization; no person may be compensated primarily to conduct solicitations.'},
 FL:{amount:50000,inclusive:false,period:'lastFiscal',conditions:['allUnpaid','unpaidFundraising','noPrivateBenefit','noExternal'],action:'Submit the annual small charitable organization application (FDACS-10110) and financial report. Monitor current year contributions: reaching $50,000 requires registration within 30 days.'},
 GA:{amount:25000,inclusive:false,period:'calendar',conditions:['noSolicitor'],action:'Document the previous and current calendar year totals and the absence of a paid solicitor.'},
 HI:{amount:25000,inclusive:false,period:'threeFiscalAverage',conditions:['noProfessional'],action:'Apply for Hawaii’s small organization exemption. Use the three year national average under Hawaii’s definition, excluding government and 501(c)(3) grants; an application is required.'},
 MN:{amount:25000,inclusive:true,period:'fiscal',conditions:['allUnpaid','noPrivateBenefit','noExternal'],action:'Confirm the exemption notice and supporting documentation with the Attorney General.'},
 NC:{amount:50000,inclusive:false,period:'calendar',conditions:['allUnpaid'],action:'Request exemption with supporting financial and compensation records; confirm all covered roles are unpaid.'},
 NY:{amount:25000,inclusive:false,period:'nyFiscal',conditions:['noProfessional'],action:'Confirm the Article 7-A small solicitation exemption using New York contributions and no professional fundraiser or fundraising counsel. A separate EPTL charitable assets registration may still apply. Under section 91.3, confirmation is optional unless the Attorney General sends a failure-to-register notice.'},
 PA:{amount:25000,inclusive:true,period:'fiscal',conditions:['noPaidSolicitation'],action:'Document gross national contributions and no compensated solicitation. Review separate purely public charity filings if applicable.'},
 RI:{amount:25000,inclusive:true,period:'fiscal',conditions:['noExternal','noPrivateBenefit'],action:'Document the self executing statutory exclusion, absence of professional fundraising and absence of officer or member benefit; monitor actual and intended receipts.'},
 SC:{amount:20000,inclusive:true,period:'calendarCurrent',conditions:['scCompensationLimit','noPrivateBenefit','noExternal'],action:'Submit the annual exemption application. Monitor public contributions and pledges; exceeding $20,000 requires registration within 30 days.'},
 TN:{amount:50000,inclusive:true,period:'fiscal',conditions:[],action:'File an annual exemption request for the small organization category.'},
 WA:{amount:50000,inclusive:false,period:'fiscal',conditions:['allUnpaid'],action:'Retain evidence of the contribution total and that all activities are unpaid.'},
 WI:{amount:25000,inclusive:true,period:'fiscal',conditions:['allUnpaid'],action:'Retain volunteer and contribution records supporting the small organization exemption.'}
};
// These fields are verified statutory bases, never substituted with the rough
// intake estimate or another state's totals. Related trust duties are separate.
Object.assign(SMALL,{
 NJ:{amount:10000,inclusive:true,period:'njFiscal',fields:['njFiscalContributions'],conditions:['njSmallRoles'],action:'Retain the current fiscal gross contribution total and role evidence. No charity registration is indicated while the statutory small route applies; Above $10,000 and up to $25,000, short-form registration is a separate route, not an exemption.'},
 MD:{amount:25000,inclusive:true,period:'mdFiscal',fields:['mdFiscalContributions'],conditions:['noSolicitor'],action:'Submit Maryland’s annual Exempt Organization Fund-Raising Notice with the financial evidence. This is simplified paperwork, not filing-free clearance.'},
 VA:{amount:5000,inclusive:true,period:'vaCalendar',fields:['calendarPrevious','vaCalendarPriorTwo','vaCalendarPriorThree','calendarActual','calendarExpected'],conditions:['unpaidFundraising','noPrivateBenefit'],action:'Submit Virginia Form 100 to request the exemption letter. Use each of the three preceding calendar years and the current calendar year, rather than a rough annual estimate.'},
 WV:{amount:50000,inclusive:true,period:'calendarCurrent',conditions:['noProfessional'],action:'Send the Secretary of State an exemption letter describing the organization, fundraising methods and expected annual revenue; retain its determination.'},
 KS:{amount:10000,inclusive:true,period:'fiscal',conditions:['unpaidFundraising'],action:'Retain actual and intended tax-period contributions and unpaid fundraising evidence. You may ask the Attorney General for written confirmation if needed.'},
 MI:{amount:25000,inclusive:true,period:'miAdjusted',fields:['miAdjustedActual','miAdjustedExpected'],conditions:['unpaidFundraising','miPublicFinancials'],action:'Submit CTS-03 with financial evidence and the schedule of government and restricted foundation grants excluded from the any-12-month contribution test. This route exempts solicitation only; charitable trust registration is assessed separately.'},
 OH:{amount:25000,inclusive:true,period:'ohAdjusted',fields:['ohAdjustedRevenue'],conditions:['ohNoPrimaryPaidSolicitation'],action:'Document adjusted gross revenue for the immediately preceding fiscal year, excluding government and 501(c) grants, and the compensation facts. This exempts solicitation only; Ohio charitable trust registration remains separate.'},
 SC:{amount:25000,inclusive:true,period:'scGross',fields:['scGrossActual','scGrossExpected'],conditions:['scCompensationLimit','noPrivateBenefit','noExternal'],action:'Submit South Carolina’s annual exemption application. Act 170, effective May 18, 2026, uses fiscal gross revenue, not calendar-year public contributions.'}
});
SMALL.AR.period='calendarCurrent';
SMALL.CT.action+=' Send the signed eligibility and officer/contact update five years after approval and every five years thereafter under 21a-190k-3(d); there is no annual exemption renewal.';
SMALL.AL.action='The statutory small-charity exemption is supported when all conditions are met. Confirm any category-specific agency claim procedure; a universal mandatory exemption claim has not been established.';
SMALL.NJ.action='Amount and role conditions can support the statutory exemption. Confirm Consumer Affairs’ category-specific claim procedure before assuming no filing. Exactly $10,000 meets the amount condition; monitor current-year crossings separately.';
SMALL.DC={amount:25000,inclusive:true,period:'dcCalendar',fields:['calendarPrevious','calendarExpected'],conditions:['allUnpaid','noPrivateBenefit'],action:'Retain prior-year actual and current-year expected contributions and unpaid-function/no-insider-benefit evidence under 16 DCMR 1301. Confirm the exempt-license process with DLCP; do not assume an unpublished inflation-adjusted amount.'};
SMALL.VA.conditions=['allUnpaid','noPrivateBenefit'];
SMALL.WA.conditions=['allUnpaid','noPrivateBenefit'];
SMALL.HI.approvalRequired=true;
SMALL.HI.action+=' Obtain Attorney General approval before relying on this exemption under HRS 467B-11.5.';
SMALL.NC.action='Retain the state-defined contributions and compensation evidence. Written exemption confirmation may be requested; do not treat an optional request as a mandatory filing.';
STATES.find(s=>s.code==='DC').sources.push({title:'Published small-solicitation regulation · adopted June 8, 2018',url:'https://dcregs.dc.gov/Common/DCMR/SectionList.aspx?SectionNumber=16-1301'});
STATES.find(s=>s.code==='TN').sources.push({url:'https://publications.tnsosfiles.com/rules/1360/1360-03/1360-03-01.20241208.pdf',title:'Internet solicitation rules · definitions and rule .07'});
STATES.find(s=>s.code==='TN').nuance='Internet: 100 resident online contributions OR $25,000 in a year. Targeting and domicile are independent triggers. Small fiscal public contributions exemption up to $50,000 requires an annual statement.';
STATES.find(s=>s.code==='CT').nuance='Small exemption uses worldwide contributions below $50,000 in two of the last three years; newer charities need a good faith estimate. CPC-54 is required to claim an exemption.';
STATES.find(s=>s.code==='CO').sources.push({url:'https://www.sos.state.co.us/pubs/charities/FAQ/registration.html',title:'Current Colorado registration and exemption FAQ'});
STATES.find(s=>s.code==='CO').categories=['religious'];
STATES.find(s=>s.code==='CO').note='Church and specified church-related categories require the federal religious return exclusion. No blanket school or university exemption is assumed. The small dollar exemption uses adjusted gross revenue, not contributions alone; the separate ten-person receipt route needs review.';
STATES.find(s=>s.code==='MO').sources.push({url:'https://ago.mo.gov/get-help/programs-services-from-a-z/charity/for-nonprofits/registration-faqs/',title:'Current Missouri registration FAQs'},{url:'https://ago.mo.gov/get-help/programs-services-from-a-z/charity/for-nonprofits/',title:'Optional agency exemption letter request'});
STATES.find(s=>s.code==='MO').note='Recognized 501(c)(3) organizations need not register. The agency offers an exemption confirmation letter if needed; attach the IRS determination to the request.';
STATES.find(s=>s.code==='SC').sources.push({url:'https://www.scstatehouse.gov/code/t33c056.php',title:'Religious exclusion versus annual exemption · sections 33-56-20 and 33-56-50'});
STATES.find(s=>s.code==='SC').note='Qualifying religious entities are excluded under section 33-56-20 and do not use the annual exemption application. Section 33-56-50 educational and small organization exemptions require annual applications.';
STATES.find(s=>s.code==='NY').sources.push({url:'https://ag.ny.gov/sites/default/files/regulatory-documents/online-reg-useguide.pdf',title:'New York contributions basis and separate registration categories'},{url:'https://www.nysenate.gov/legislation/laws/EXC/172-A',title:'Article 7-A exemptions and paid fundraising restrictions'});
export const NO_GENERAL_STATES=['DE','ID','IN','IA','MT','NE','SD','VT','WY'];
export const LABELS={required:'Registration indicated',exemption:'Potential exemption / simplified filing',none:'No general registration indicated',review:'Review needed',outside:'Outside stated activity'};

// Core framework updates verified October 6, 2026. Exemption facts still need
// separate confirmation; a 501(c)(3) determination is not blanket clearance.
for(const code of ['DC','OK']){
 const s=STATES.find(s=>s.code===code);s.mode='solicit';s.reviewed='2026-10-06';s.coverage='Core solicitation framework verified; exemptions evaluated separately';
}
Object.assign(STATES.find(s=>s.code==='DC'),{note:'Covered solicitation requires a District charitable solicitation license unless a statutory or regulatory exemption applies.',nuance:'Church-controlled and membership-only solicitations have distinct exclusions. The statutory ceiling for regulatory small-solicitation relief is inflation-adjusted; do not assume a fixed $25,000 exemption.',sources:[{title:'DC Code 44-1703 · registration and exceptions',url:'https://code.dccouncil.gov/us/dc/council/code/sections/44-1703'},{title:'DLCP charitable services licensing',url:'https://dlcp.dc.gov/page/charitable-services-business-0'}]});
Object.assign(STATES.find(s=>s.code==='OK'),{note:'Covered solicitation requires Secretary of State registration unless section 552.4 applies. Federal 501(c)(3) status is not a state registration exemption.',nuance:'The $10,000 figure does not provide a general small-charity exemption. Religious, educational and other statutory categories have qualifying conditions. Use the actual institutional criteria; no blanket small-dollar exclusion is applied.',sources:[{title:'Attorney General · current solicitation requirements and exclusions',url:'https://oklahoma.gov/oag/about/divisions/charity-enforcement.html'},{title:'Secretary of State · charitable organizations',url:'https://www.sos.ok.gov/charity/Default.aspx'},{title:'Attorney General · applicable statutory exclusions',url:'https://oklahoma.gov/oag/about/divisions/charity-enforcement.html'}]});

STATES.find(s=>s.code==='PA').sources.push({url:'https://www.legis.state.pa.us/WU01/LI/LI/US/HTM/1990/0/0202..HTM',title:'Pennsylvania Solicitation Act · section 3 religious exclusion'});

// Per-profile dates identify the rules actually reviewed, not a blanket legal certification.
const coverageSources={
 AL:'https://www.alabamaag.gov/licensing-registration/charitable-organizations/',
 AR:'https://www.sos.arkansas.gov/uploads/bcs/SoS_-CharitableRegistrationInArkansas_5.2025_.pdf',
 CA:'https://oag.ca.gov/charities/initial-reg',
 CO:'https://www.sos.state.co.us/pubs/charities/FAQ/registration.html',
 MN:'https://www.revisor.mn.gov/statutes/cite/309.515',
 MS:'https://charities.sos.ms.gov/online/portal/default/page/instructions/Portal.aspx',
 NV:'https://www.leg.state.nv.us/NRS/NRS-082A.html',
 NH:'https://gc.nh.gov/rsa/html/I/7/7-19.htm',
 NM:'https://nmag.gov/get-help/charities/',
 ND:'https://www.legis.nd.gov/cencode/t50c22.pdf',
 OR:'https://www.oregonlegislature.gov/bills_laws/ors/ors128.html',
 RI:'https://webserver.rilegislature.gov/Statutes/TITLE5/5-53.1/5-53.1-3.htm',
 WA:'https://www.sos.wa.gov/corporations-charities/frequently-asked-questions-faqs/charitable-organizations-frequently-asked-questions',
 AK:'https://law.alaska.gov/department/civil/consumer/charityreg.html',
 KS:'https://www.kslegislature.gov/b2025_26/laws/017_000_0000_chapter/017_017_0000_article/017_017_0062_section/017_017_0062_k/',
 ME:'https://www.legislature.maine.gov/legis/statutes/9/title9sec5006.html',
 MD:'https://sos.maryland.gov/documents/exemptorganizationfund.pdf',
 MI:'https://www.michigan.gov/consumerprotection/-/media/Project/Websites/AG/charities/registration-forms/Request-for-Exemption-CTS-3.pdf',
 NJ:'https://www.njconsumeraffairs.gov/charities/Pages/FAQ.aspx',
 OH:'https://codes.ohio.gov/ohio-administrative-code/rule-109:1-1-02',
 VA:'https://law.lis.virginia.gov/vacode/title57/chapter5/section57-60/',
 WV:'https://code.wvlegislature.gov/29-19-6/',
 SC:'https://www.scstatehouse.gov/sess126_2025-2026/bills/715.htm',
 NY:'https://ag.ny.gov/sites/default/files/regulatory-documents/Regs-F.pdf',
 IL:'https://illinoisattorneygeneral.gov/Page-Attachments/ILCharitableOrganizLaws.pdf',
 GA:'https://sos.ga.gov/page/charities-division-faq',
 MA:'https://www.mass.gov/regulations/940-CMR-200-regulations-of-the-director-of-public-charities',
 KY:'https://www.ag.ky.gov/Resources/Consumer-Resources/charity/Pages/registration.aspx',
 UT:'https://commerce.utah.gov/dcp/for-businesses/charities/'
};
for(const [code,url]of Object.entries(coverageSources)){
 const s=STATES.find(s=>s.code===code);s.reviewed='2026-10-06';s.sources.push({title:'Current requirements and exemption source reviewed October 6, 2026',url});
 if(SMALL[code])s.nuance=SMALL[code].action;
}
STATES.find(s=>s.code==='SC').nuance='Act 170 (effective May 18, 2026): fiscal gross revenue up to $10,000 regardless of professional fundraising, or up to $25,000 with the specified compensation and provider conditions. Annual exemption application remains required.';
STATES.find(s=>s.code==='WV').sources.push({title:'Current agency exemption-letter instructions',url:'https://sos.wv.gov/charities-frequently-asked-questions'});
STATES.find(s=>s.code==='NJ').sources.push({title:'Enacted section 45:17A-26 · State Law Library legislative record',url:'https://repo.njstatelib.org/server/api/core/bitstreams/7cca27f9-e045-4ab3-b229-0538f1a4a7f7/content'});
STATES.find(s=>s.code==='TN').sources.push({title:'2024 enacted definitions · Public Chapter 533',url:'https://publications.tnsosfiles.com/acts/113/pub/pc0533.pdf'});
