"""Selected-record response reuse must preserve identity, dates and fallback."""
import ast
import json
from pathlib import Path
import subprocess
from types import SimpleNamespace
import unittest
from unittest.mock import MagicMock, patch
import registry_snapshot_server as m

SELECTION = {'charityName': 'Example Relief', 'numberOfResults': '16',
    'accountId': '11111111-1111-1111-1111-111111111111',
    'charityRegistrationId': '22222222-2222-2222-2222-222222222222'}
BODY = '''<html><body><input id="crsm_federalein" value="123456789">
<input id="accountnumber" value="CH12345">
<input id="crsm_fiscalyearenddate" value="2025-12-31T00:00:00">
</body></html><!-- Generated by the public portal --><!-- Page OK -->'''


class NewJerseyPublicDetailTests(unittest.TestCase):
    def setUp(self):
        self.org = m.checker.Organization('Example Relief', '12-3456789')
        self.page = MagicMock()
        self.page.url = 'https://charportal.dca.njoag.gov/Charity-Registration/CHR-Public-Search-Page/'
        self.target = MagicMock()
        self.target.evaluate.return_value = {'name': 'Example Relief', 'ein': '123456789', 'credential': 'CH12345'}
        self.responses = []
        for name in ('CAPTURE_EVIDENCE_SCREENSHOTS', 'CAPTURE_LIGHTWEIGHT_SOURCE_SNAPSHOT'):
            p = patch.object(m, name, False); p.start(); self.addCleanup(p.stop)

    def run_detail(self, selection=None, body=BODY, **change):
        def get(url, **kwargs):
            first = '/retrieveRegistration/' in url
            response = MagicMock(url=url, status=200, headers={'content-type': 'application/json' if first else 'text/html'})
            response.body.return_value = json.dumps(SELECTION if selection is None else selection).encode() if first else body.encode()
            for key, value in change.items():setattr(response, key, value)
            self.responses.append(response)
            return response
        self.page.request.get.side_effect = get
        return m.nj_selected_public_detail(self.page, self.target, self.org)

    def test_history_count_can_exceed_one_but_ein_and_credential_must_bind(self):
        self.assertEqual(self.run_detail(), BODY)
        self.assertEqual(self.page.request.get.call_count, 2)
        for call in self.page.request.get.call_args_list:
            self.assertEqual(call.kwargs['max_redirects'], 0)
            self.assertLessEqual(call.kwargs['timeout'], 4000)
        self.assertTrue(all(r.dispose.call_count == 1 for r in self.responses))

    def test_wrong_or_duplicate_detail_identity_is_never_accepted(self):
        for body in (BODY.replace('123456789', '987654321'), BODY.replace('CH12345', 'CH54321'),
                     BODY.replace('</body>', '<input id="crsm_federalein" value="123456789"></body>')):
            with self.subTest(body=body):self.assertEqual(self.run_detail(body=body), '')

    def test_incomplete_or_missing_filing_period_keeps_browser_path(self):
        for body in (BODY.replace('</html>', ''), BODY + '<script>incomplete',
                     BODY.replace('crsm_fiscalyearenddate', 'unrelated'), '<html>Verify you are human</html>'):
            with self.subTest(body=body):self.assertEqual(self.run_detail(body=body), '')

    def test_selection_has_to_identify_the_scored_row(self):
        for change in ({'charityName': 'Different Relief'}, {'accountId': '../other'},
                       {'numberOfResults': '0'}, {'numberOfResults': 'unknown'}, {'charityRegistrationId': None}):
            with self.subTest(change=change):self.assertEqual(self.run_detail(selection={**SELECTION, **change}), '')

    def test_failed_or_redirected_requests_do_not_become_negative_results(self):
        for change in ({'url': 'https://unrelated.example/detail'}, {'status': 503},
                       {'headers': {'content-type': 'text/plain'}}):
            with self.subTest(change=change):self.assertEqual(self.run_detail(**change), '')
        self.page.request.get.side_effect = TimeoutError('state response incomplete')
        self.assertEqual(m.nj_selected_public_detail(self.page, self.target, self.org), '')

    def test_no_exact_ein_row_and_evidence_capture_do_not_issue_requests(self):
        self.target.evaluate.return_value['ein'] = '987654321'
        self.assertEqual(m.nj_selected_public_detail(self.page, self.target, self.org), '')
        self.target.evaluate.return_value['ein'] = '123456789'
        self.org.evidence_mode = True
        self.assertEqual(m.nj_selected_public_detail(self.page, self.target, self.org), '')
        self.page.request.get.assert_not_called()

    def test_cache_is_scoped_to_this_page_url_ein_and_name(self):
        key = (self.page.url, '123456789', self.org.organization_name)
        self.page._cc_nj_selected_detail = (key, BODY)
        with patch.object(m, 'registry_page_body', side_effect=RuntimeError('uncached browser path')):
            self.assertEqual(m.nj_detail_body(self.page, self.org), BODY)
            for org in (m.checker.Organization('Example Chapter', '123456789'),
                        m.checker.Organization('Example Relief', '987654321'),
                        m.checker.Organization('Example Relief', '123456789', evidence_mode=True)):
                with self.assertRaisesRegex(RuntimeError, 'uncached browser path'):m.nj_detail_body(self.page, org)
            self.page.url += '?changed'
            with self.assertRaisesRegex(RuntimeError, 'uncached browser path'):m.nj_detail_body(self.page, self.org)

    def test_new_search_discards_previously_completed_response(self):
        self.page._cc_nj_selected_detail = ('old', BODY)
        self.page.goto.side_effect = RuntimeError('stop test navigation')
        m.search_nj_direct(self.page, self.org)
        self.assertIsNone(self.page._cc_nj_selected_detail)

    def test_real_browser_uses_selected_row_not_first_result(self):
        # APIRequestContext does not use page routes; bind an explicit request
        # mock while retaining real row selection, DOM scoring, and click checks.
        with m.checker.sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            try:
                page = browser.new_page()
                page.set_content('''<div role="row"><div data-automation-key="name"><button class="ms-Link">Example Relief Chapter</button></div>
                <div data-automation-key="crsm_federalein">987654321</div><div data-automation-key="accountnumber">CH54321</div></div>
                <div role="row"><div data-automation-key="name"><button class="ms-Link">Example Relief</button></div>
                <div data-automation-key="crsm_federalein">123456789</div><div data-automation-key="accountnumber">CH12345</div></div>''')
                self.run_detail()  # configure mocked public responses
                with patch.object(type(page.request), 'get', side_effect=self.page.request.get.side_effect) as get:
                    actual = m.nj_detail_body(page, self.org)
                    self.assertIn(BODY, actual)
                    self.assertIn('chNum=CH12345', get.call_args_list[0].args[0])
                    self.assertEqual(m.nj_detail_body(page, self.org), actual)
                    self.assertEqual(get.call_count, 2)
            finally:browser.close()

    def test_total_request_allowance_does_not_reset_between_responses(self):
        clock = [0.0]
        first = MagicMock(url='https://charportal.dca.njoag.gov/retrieveRegistration/', status=200,
                          headers={'content-type': 'application/json'})
        first.body.return_value = json.dumps(SELECTION).encode()
        def get(*args, **kwargs):
            clock[0] = 7.0
            return first
        self.page.request.get.side_effect = get
        with patch.object(m.time, 'monotonic', side_effect=lambda: clock[0]):
            self.assertEqual(m.nj_selected_public_detail(self.page, self.target, self.org), '')
        self.page.request.get.assert_called_once()

    def test_remaining_master_scoring_matching_and_classification_unchanged(self):
        from testing.capacity_lab.parsing_scope import strip_nj_public_detail_optimization
        root = Path(m.__file__).parent
        old = ast.parse(subprocess.check_output(['git', 'show', '914fa6f:registry_snapshot_server.py'], cwd=root).decode('utf-8'))
        new = ast.parse(Path(m.__file__).read_text(encoding='utf-8'))
        strip_nj_public_detail_optimization(new)
        self.assertEqual(ast.dump(old), ast.dump(new))


if __name__ == '__main__':unittest.main()
